name: transfer_arm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  common_library:
    path: ./common_library
  flutter_screenutil: ^5.8.2
  go_router: ^7.1.1
  provider: ^6.0.5
  flutter_sticky_header: ^0.6.5
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - images/

